# Enable -shell-escape flag in LaTeX Workshop extension for VS Code. Also:
# - Do not change the output build directory, or build will fail.
# - Delete *.w18 auxiliry files generated by -shell-escape. This is optional.
# This flag is necessary for language syntax highlighting using the minted
# package. As stated before, do not change the output directory when using
# pdflatex and minted because the build will fail.
$pdflatex='pdflatex -shell-escape';
