#!/usr/bin/env bash
C_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "\.[ch]$")
CXX_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "\.([chi](pp|xx)|(cc|hh|ii)|[CHI])$")
/usr/bin/env clang-format -i -style=file ${CXX_CHANGED_FILES}
